//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelManagement.EntityLayer.DataEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblBooking
    {
        public int BookingId { get; set; }
        public Nullable<System.DateTime> BookingDate { get; set; }
        public Nullable<int> RoomId { get; set; }
        public Nullable<int> StatusId { get; set; }
    
        public virtual tblRoom tblRoom { get; set; }
        public virtual tblStatu tblStatu { get; set; }
    }
}
